### ISSUE TITLE
Saturation glyph steals all mana - Ultimate Armour

### ISSUE THREAD

**Issue by Joh0210** [Joh0210/DragonMagicAndRelics#17]
There is a slight incompatibility with Goety. When you're a Lich (goety), and you have a saturation upgrade, your mana will continuously drain as it tries to feed you. Reason for this is that if you are a Lich with Goety, your hunger will be automatically set to a low amount, and kept on that.

And some other effekt of Ultimate Armour drains all the mana of Lichs

**Comment by Joh0210** [comment]
An error that also seems to be thrown from time to time when Ultimate Armor is active:

```
[13:33:21] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: com/ibm/icu/impl/IllegalIcuArgumentException
        Index: 2
        Listeners:
                0: NORMAL
                1: ASM: class de.joh.dmnr.common.event.MagicEventHandler onSpellCast(Lcom/mna/api/events/SpellCastEvent;)V
                2: ASM: class de.joh.fnc.compat.dmnr.common.event.AddonDmnrCommonEventHandler onSpellCast(Lcom/mna/api/events/SpellCastEvent;)V
                3: ASM: class de.joh.fnc.common.event.MagicEventHandler onSpellCast(Lcom/mna/api/events/SpellCastEvent;)V
                4: ASM: class com.mna.spells.SpellCastEvents onSpellCast(Lcom/mna/api/events/SpellCastEvent;)V
java.lang.NoClassDefFoundError: com/ibm/icu/impl/IllegalIcuArgumentException
        at TRANSFORMER/fnc@1.2.6/de.joh.fnc.compat.dmnr.common.event.AddonDmnrCommonEventHandler.onSpellCast(AddonDmnrCommonEventHandler.java:91)
        at TRANSFORMER/fnc@1.2.6/de.joh.fnc.compat.dmnr.common.event.__AddonDmnrCommonEventHandler_onSpellCast_SpellCastEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/mna@3.1.0.1/com.mna.events.EventDispatcher.DispatchSpellCast(EventDispatcher.java:82)
        at TRANSFORMER/mna@3.1.0.1/com.mna.spells.SpellCaster.Affect(SpellCaster.java:317)
        at TRANSFORMER/mna@3.1.0.1/com.mna.spells.SpellCaster.PlayerCast(SpellCaster.java:239)
        at TRANSFORMER/mna@3.1.0.1/com.mna.items.sorcery.ItemSpell.castSpellOnUse(ItemSpell.java:79)
        at TRANSFORMER/mna@3.1.0.1/com.mna.items.relic.ItemAstroBlade.m_7203_(ItemAstroBlade.java:185)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:275)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1087)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.ibm.icu.impl.IllegalIcuArgumentException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 29 more
```
